name: auditmysite_engine
description: Engine for crawling sitemaps, auditing pages via CDP + axe-core
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shared:
    path: ../shared
  puppeteer: ^3.11.0
  http: ^1.2.0
  archive: ^3.4.0
  xml: ^6.5.0
  args: ^2.5.0
  logging: ^1.2.0
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_web_socket: ^2.0.0
  shelf_cors_headers: ^0.1.5
  pdf: ^3.10.0
  intl: ^0.19.0
  html: ^0.15.4

dev_dependencies:
  lints: ^3.0.0
