name: auditmysite_studio
description: Flutter Desktop GUI for auditmysite
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  auditmysite_engine:
    path: ../auditmysite_engine
  http: ^1.2.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  path: ^1.9.0
  web_socket_channel: ^2.4.0
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  process_run: ^0.12.5
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
